1:
	gcc -o generateDatabases wordsToDatabases.c
	./generateDatabases πεθαίνω

2:
	gcc -o generateVerbs verbsCreator.c
	./generateVerbs

3:
	gcc -o checkHeart verbsChecker.c
	./checkHeart πεθαίνω

clean:
	rm  generateDatabases generateVerbs checkHeart
	rm ../generatedDatabases/greekRimata.txt ../generatedDatabases/greekRimataCreator.txt ../generatedDatabases/greekYpoloipa.txt

