1: # THIS IS TO CREATE WORDS FILE
	gcc -o generateDatabases wordsToDatabases.c
	./generateDatabases

2:
	gcc -o generateVerbs verbInfoFinder.c verbCreatingFunctions/functionsForXronous.c verbCreatingFunctions/xronoi.c
	clear
	./generateVerbs παγιδεύψαμε

3:
	gcc -o checkHeart verbsChecker.c
	./checkHeart παγιδεύψαμε

clean:
	rm  generateDatabases generateVerbs checkHeart verbId
	rm ../generatedDatabases/greekRimata.txt 
	rm ../generatedDatabases/greekRimataCreator.txt 
	rm ../generatedDatabases/greekYpoloipa.txt
	rm ../generatedDatabases/greekRimataCreator.txtSorted.txt