find:
	gcc -Werror -o wordExifGr wordExifGr.c
	./wordExifGr ζηλεύω
check:
	gcc -Werror -o wordExif wordExplanation.c
	./wordExif παίζω

data:
	gcc -Werror -o creator readDatabase.c
	./creator

clean:
	rm  wordExifGr